const leaderboardData = [
  { name: "Aaradhya Vaidehi", total: 43 , branch: "ISRO" },
  { name: "Amrit Kinu R R", total: 0 , branch: "Mylaudy" },
  { name: "Ananya Rajan P", total: 32, branch: "Online" },
  { name: "Anbu Kumar C", total: 0 , branch: "Mylaudy" },
  { name: "Antonin Ransica A K", total: 0, branch: "Mylaudy" },
  { name: "Devin R J", total: 0, branch: "Mylaudy" },
  { name: "Dhakshan A P", total: 24, branch: "Mylaudy" },
  { name: "Jaden Matteo A L", total: 35, branch: "ISRO" },
  { name: "Karmuhilan S", total: 0, branch: "ISRO" },
  { name: "Mahasree A V", total: 24, branch: "Nagercoil" },
  { name: "Muthish E G", total: 39, branch: "Mylaudy" },
  { name: "Nainika N K", total: 24, branch: "Mylaudy" },
  { name: "Nousith Siva J S", total: 61, branch: "Mylaudy" },
  { name: "Radha Krishnan I", total: 48, branch: "Nagercoil" },
  { name: "Ragav Krishna N", total: 96, branch: "Nagercoil" },
  { name: "Ramnath Revanth S", total: 0, branch: "Mylaudy" },
  { name: "Sairam R M", total: 24, branch: "ISRO" },
  { name: "Sanjeev K S", total: 0, branch: "Mylaudy" },
  { name: "Shahida S", total: 0, branch: "ISRO" },
  { name: "Sree Maha K", total: 87, branch: "Nagercoil" },
  { name: "Sree Nasrisha S J", total: 8, branch: "Nagercoil" },
  { name: "Sri Rakshan S J", total: 7, branch: "Nagercoil" },
  { name: "Supratik R D", total: 0, branch: "Nagercoil" },
  { name: "Vijay Krishna A N", total: 47, branch: "Nagercoil" },
];