const leaderboardData = [
  { name: "Aaradhya Vaidehi", total: 24 , branch: "ISRO" },
  { name: "Akshitha R R", total: 0, branch: "Mylaudy" },
  { name: "Amrit Kinu R R", total: 0 , branch: "Mylaudy" },
  { name: "Ananya Rajan P", total: 32, branch: "Online" },
  { name: "Anbu Kumar C", total: 0 , branch: "Mylaudy" },
  { name: "Antonin Ransica A K", total: 0, branch: "Mylaudy" },
  { name: "Atul Gupta", total: 0, branch: "ISRO" },
  { name: "Chris Matteo A L", total: 0, branch: "ISRO" },
  { name: "Devin R J", total: 0, branch: "Mylaudy" },
  { name: "Dhakshan A P", total: 22, branch: "Mylaudy" },
  { name: "Jaden Matteo A L", total: 24, branch: "ISRO" },
  { name: "Karmuhilan S", total: 0, branch: "ISRO" },
  { name: "Mahasree A V", total: 24, branch: "Nagercoil" },
  { name: "Mithun Satvik M S", total: 0, branch: "Nagercoil" },
  { name: "Muthish E G", total: 23, branch: "Mylaudy" },
  { name: "Nainika N K", total: 24, branch: "Mylaudy" },
  { name: "Niha Hari", total: 0, branch: "Nagercoil" },
  { name: "Nithwik J S", total: 0, branch: "Nagercoil" },
  { name: "Nousith Siva J S", total: 0, branch: "Mylaudy" },
  { name: "Pratyush B", total: 0, branch: "Nagercoil" },
  { name: "Radha Krishnan I", total: 0, branch: "Nagercoil" },
  { name: "Ragav Krishna N", total: 0, branch: "Nagercoil" },
  { name: "Ramnath Revanth S", total: 0, branch: "Mylaudy" },
  { name: "Rissvanth R", total: 0, branch: "Mylaudy" },
  { name: "Riddhi Gupta", total: 0, branch: "ISRO" },
  { name: "Sairam R M", total: 24, branch: "ISRO" },
  { name: "Sanjeev K S", total: 0, branch: "Mylaudy" },
  { name: "Shahida S", total: 0, branch: "ISRO" },
  { name: "Sree Maha K", total: 24, branch: "Nagercoil" },
  { name: "Srinika S M", total: 0, branch: "Nagercoil" },
  { name: "Srithik Ram R D", total: 0, branch: "Nagercoil" },
  { name: "Supratik R D", total: 0, branch: "Nagercoil" },
  { name: "Suvethika Thamizh S", total: 0, branch: "Mylaudy" },
  { name: "Vijay Krishna A N", total: 0, branch: "Nagercoil" },
];